import type { Metadata } from "next";
import { Inter, Ubuntu, Oxygen } from "next/font/google";
import "./globals.css";

const inter = Oxygen({ subsets: ["latin"], weight:"400" });

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by love",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200 text-slate-900`}>{children}</body>
    </html>
  );
}
