import type { Metadata } from "next";
import { Inter, Ubuntu, Oxygen, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/storeProvider";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by love",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} bg-slate-200 text-slate-900`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
